flask/fundamentals/Dojo Survey/app/forms.py
from enum import Enum
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class Locations(Enum):
    """
    Enumeration representing different dojo locations.
    
    Attributes:
        Select: Placeholder prompting users to select a location.
        Tunis: Represents the dojo location in Tunis, TN.
        Bellevue: Represents the dojo location in Bellevue, WA.
        Silicon_Valley: Represents the dojo location in Silicon Valley, CA.
        Los_Angeles: Represents the dojo location in Los Angeles, CA.
    """
    Select = "---- Select a location ----"
    Tunis = "Tunis, TN"
    Bellevue = "Bellevue, WA"
    Silicon_Valley = "Silicon Valley, CA"
    Los_Angeles = "Los Angeles, CA"

class Languages(Enum):
    """
    Enumeration representing different programming languages.
    
    Attributes:
        Select: Placeholder prompting users to select a language.
        Python: Represents the Python programming language.
        Java: Represents the Java programming language.
        JS: Represents the JavaScript programming language.
        C_Sharp: Represents the C# programming language.
        DotNet: Represents the .NET framework.
    """
    Select = "---- Select a language ----"
    Python = "Python"
    Java = "Java"
    JS = "JavaScript"
    C_Sharp = "C#"
    DotNet = ".NET"

# Workaround to include "C#" and ".NET" as choices in the SelectField
lang_choices = [
    (Languages.Select, "---- Select a language ----"),
    (Languages.Python, "Python"),
    (Languages.Java, "Java"),
    (Languages.JS, "JavaScript"),
    (Languages.C_Sharp, "C#"),
    (Languages.DotNet, ".NET")
]

class SurveyForm(FlaskForm):
    """
    FlaskForm derived class representing the survey form.

    Attributes:
        name (StringField): Field to collect the user's name. It is a required field.
        location (SelectField): Dropdown field to select the dojo location. It is a required field.
        fav_lang (SelectField): Dropdown field to select the favorite programming language. It utilizes the lang_choices list to include "C#" and ".NET" as choices. 
        additional (TextAreaField): Text area field to collect additional information from the user.
        submit (SubmitField): Button to submit the form.
    """
    name = StringField(label="Name:", validators=[DataRequired()])
    location = SelectField(label="Dojo Location:", choices=[(loc.name, loc.value) for loc in Locations],
                           validators=[DataRequired()])
    fav_lang = SelectField(label="Favorite Language", choices=[(name.value, value) for name, value in lang_choices])
    additional = TextAreaField(label="Additional Information",  render_kw={"rows": 10, "cols": 11})
    submit = SubmitField("Submit")

flask/fundamentals/Dojo Survey/app/routes.py
from flask import Blueprint
from . import views

bp = Blueprint("dojo_survey", __name__)

bp.add_url_rule("/", "index", view_func=views.index)
bp.add_url_rule("/process", "process", view_func=views.process, methods=["POST"])
bp.add_url_rule("/result", "result", view_func=views.result)

flask/fundamentals/Dojo Survey/app/views.py
from .forms import SurveyForm
from flask import request, render_template, session, redirect, url_for

def index():
    """
    View function to render the home page with the survey form.
    
    It initializes a SurveyForm instance and passes it to the 'index.html' template.
    
    Returns:
        render_template: Renders and returns the 'index.html' template with the SurveyForm instance.
    """
    form = SurveyForm()
    return render_template("index.html", form=form)

def process():
    """
    View function to handle form submission and store data in the session.
    
    It retrieves the form data from the POST request and stores it in the Flask session.
    Then, it redirects the user to the 'result' view function to display the survey results.
    
    Returns:
        redirect: Redirects the user to the 'result' view function.
    """
    session["name"] = request.form.get("name")
    session["location"] = request.form.get("location")
    session["fav_lang"] = request.form.get("fav_lang")
    session["additional"] = request.form.get("additional")

    return redirect(url_for("dojo_survey.result"))

def result():
    """
    View function to display the survey results.
    
    It retrieves the survey data stored in the session and creates a dictionary to organize the data.
    Then, it passes the data to the 'result.html' template to display the survey results.
    
    Returns:
        render_template: Renders and returns the 'result.html' template with the survey data.
    """
    survey_info = {
        "Name": session.get("name"),
        "Location": session.get("location"),
        "Favorite Language": session.get("fav_lang"),
        "Additional Information": session.get("additional")
    }
    return render_template("result.html", data=survey_info)

flask/fundamentals/Dojo Survey/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgo=">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}"">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Dojo Survey</title>
</head>
<body>
    <main class="container-sm">
        <form action="{{ url_for('process') }}" method="POST">
            <h1 id="title">Dojo Servey</h1>
            {{ form.hidden_tag() }}
            <div class="form-group">
                {% for field in form %}
                    {% if field.name != "csrf_token" and field.type != "SubmitField" %}
                        {{ field.label }} 
                        {{ field(class="form-control") }}
                    {% endif %}
                {% endfor %}
                {{form.submit(class="btn btn-primary")}}
            </div>
        </form>
    </main>
</body>
</html>

flask/fundamentals/Dojo Survey/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="data:image/png;base64,iVBORw0KGgo=">
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}"">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Dojo Survey</title>
</head>
<body>
    <main class="container-sm result">
        <h1 id="user_name">{{data.name}}</h1>
        <div>
            {% for key, value in data.items() %}
                {% if key != "name" %}
                    <p> {{ key }}:  {{ value }}</p>
                {% endif %}
            {% endfor %}
        </div>
        <a class="btn btn-link" href="{{ url_for('dojo_survey.index') }}">Go Back</a>
    </main>
</body>
</html>