flask_mysql/crud/Dojos and Ninjas/app/controllers/urls.py
from flask import Blueprint
from app.controllers import views as vw

# Create Blueprints objects to define routes
ninja = Blueprint("ninja", __name__)
dojo = Blueprint("dojo", __name__)

# Dojo related routes
dojo.add_url_rule("/", "home", view_func=vw.index)
dojo.add_url_rule("/dojos/", "list_all", view_func=vw.display_dojos)
dojo.add_url_rule("/dojo/create", "create", view_func=vw.add_dojo, methods=["POST"])
dojo.add_url_rule("/dojo/<int:id>/", "details", view_func=vw.ninjas_per_dojo)

# Ninja related routes
ninja.add_url_rule("/ninjas", "new_ninja", view_func=vw.new_ninja)
ninja.add_url_rule("/ninjas/create", "create", view_func=vw.add_ninja, methods=["POST"])

flask_mysql/crud/Dojos and Ninjas/app/models/dojo.py
from __future__ import annotations
import os
from app.config.mysqlconnection import connectToMySQL

db = os.environ.get("DB")

class Dojo:
    """
    Represents a Dojo with methods to interact with the database.
    
    Attributes:
        id (int): The ID of the dojo.
        name (str): The name of the dojo.
        created_at (datetime): The creation timestamp of the dojo.
        updated_at (datetime): The last update timestamp of the dojo.
    """
    def __init__(self, data: dict) -> None:
        """
        Initializes the Dojo object with given data.
        
        Args:
            data (dict): A dictionary containing data about the dojo. Expected keys:
                - 'id': The ID of the dojo.
                - 'name': The name of the dojo.
                - 'created_at': The creation timestamp of the dojo.
                - 'updated_at': The last update timestamp of the dojo.
        """
        self.id = data["id"]
        self.name = data["name"]
        self.created_at = data['created_at']
        self.updated_at = data['updated_at']

    @classmethod
    def get_all(cls) -> list[Dojo]:
        """
        Gets all dojos from the database.

        Returns:
            list[Dojo]: A list of Dojo objects representing all dojos in the database.
        """
        query = "SELECT * FROM dojos;"
        results = connectToMySQL(db).query_db(query)

        dojos = [cls(dojo) for dojo in results]
        return dojos
    
    @classmethod
    def get_by_id(cls, data: dict) -> Dojo:
        """
        Retrieves a dojo from the database using its id.

        Args:
            data (dict): A dictionary containing the id of the dojo to retrieve. Expected keys:
                - 'id': The ID of the dojo.

        Returns:
            Dojo: A Dojo object representing the dojo with the given id in the database.
        """
        query = "SELECT * FROM dojos WHERE id=%(id)s;"
        results = connectToMySQL(db).query_db(query, data)

        return cls(results[0])

    @classmethod
    def save(cls, data: dict) -> int:
        """
        Saves a new dojo to the database.

        Args:
            data (dict): The data dictionary containing dojo information. Expected keys:
                - 'name': The dojo's name.

        Returns:
            int: The ID of the newly created dojo.
        """
        query = "INSERT INTO dojos (name) VALUES (%(name)s)"
        return connectToMySQL(db).query_db(query, data)
    
    @classmethod
    def get_ninjas(cls, data: dict) -> list[dict]:
        """
        Retrieves ninjas associated with a specific dojo from the database.

        Args:
            data (dict): A dictionary containing the id of the dojo. Expected keys:
                - 'id': The ID of the dojo.

        Returns:
            list[dict]: A list of dictionaries where each dictionary contains information about a ninja.
        """
        query = "SELECT first_name, last_name, age FROM ninjas LEFT JOIN dojos ON dojos.id = dojo_id WHERE dojos.id = %(id)s;"

        return connectToMySQL(db).query_db(query, data)

flask_mysql/crud/Dojos and Ninjas/app/controllers/views.py
from flask import redirect, url_for, render_template, request, Response

from app.models.dojo import Dojo
from app.models.ninja import Ninja
from app.controllers.forms import DojoForm, NinjaForm

def index() -> Response:
    """Redirects to the listing of all dojos."""
    return redirect(url_for("dojo.list_all"))

def display_dojos() -> str:
    """
    Renders the main page displaying all dojos and a form to create a new dojo.

    Returns:
        render_template: Renders the 'index.html' template with all dojos and a creation form.
    """
    form = DojoForm()
    dojos = Dojo.get_all()

    return render_template("index.html", dojos=dojos, form=form)

def add_dojo() -> Response:
    """
    Adds a new dojo to the database and redirects to the main page.

    Returns:
        redirect: Redirects to the main page.
    """
    Dojo.save(request.form.to_dict())

    return redirect(url_for("dojo.list_all"))

def ninjas_per_dojo(id: int) -> str:
    """
    Render a template displaying a specific dojo and its associated ninjas.

    Args:
        id (int): The ID of the dojo.

    Returns:
        render_template: Renders the "dojo.html" template with the specified dojo and its ninjas.
    """
    data = {"id": id}
    dojo = Dojo.get_by_id(data)
    ninjas = Dojo.get_ninjas(data)

    return render_template("dojo.html", dojo=dojo, dojo_ninjas=ninjas)

def new_ninja() -> str:
    """
    Render a form to add a new ninja, with the dropdown choices for dojos dynamically populated.

    Returns:
        render_template: Renders the "add_ninja.html" template with the NinjaForm, 
                         where the 'dojo_id' field choices are set to all available dojos.
    """
    form = NinjaForm()
    form.dojo_id.choices = [(dojo.id, dojo.name) for dojo in Dojo.get_all()]
    return render_template("add_ninja.html", form=form)

def add_ninja() -> Response:
    """
    Save a new ninja to the database and redirect to the dojo's details page.

    Returns:
        redirect: Redirects to the details page of the dojo associated with the added ninja.
    """
    Ninja.save(request.form.to_dict())

    return redirect(url_for("dojo.details", id=request.form.get("dojo_id")))

flask_mysql/crud/Dojos and Ninjas/app/templates/add_ninja.html
{% extends "layout.html" %}

{% block title %} New Ninja {% endblock title %}

{% block content %}

<div class="row d-flex justify-content-between">
    <div class="col col-md-8">
        <div class="h1 mb-4">New Ninja</div>
        <form action="{{ url_for('ninja.create') }}" method="post">
            {{ form.hidden_tag() }}
            {% for field in form %}
                {% if field.name != "csrf_token" and field.type != "SubmitField" %}
                    <div class="row align-items-center m-lg-2">
                        <div class="col-md-3 mt-lg-4">
                            {{ field.label(class="form-label") }}:
                        </div>
                        {% if field.name == "dojo_id" %}
                            <div class="col-md-5 mt-lg-4">
                                {{ field(class="form-select") }}
                            </div>
                        {% else %}
                            <div class="col-md-5 mt-lg-4">
                                {{ field(class="form-control") }}
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endfor %}
            <div class="col-md-3 mt-4 offset-md-3 ps-3">
                {{form.submit(class="btn btn-primary")}}
            </div>
        </form>
    </div>
    <div class="mt-lg-5">
        <a href="{{ url_for('dojo.list_all') }}" class="link-primary">Home</a>
    </div>
</div>

{% endblock %}

flask_mysql/crud/Dojos and Ninjas/app/templates/dojo.html
{% extends "layout.html" %}

{% block title %} Dojo Show {% endblock title %}

{% block content %}

<div class="row d-flex justify-content-between">
    <div class="col col-md-5">
        <h1>{{dojo.name}} Ninjas</h1>
        <!-- <div id="dojo_list" class="border border-dark border-2 mt-4">
            {% for ninja in dojo_ninjas %}
                <div class="m-2">
                    {{ninja.first_name}}
                </div>
            {% endfor %}
        </div> -->
        {% if not dojo_ninjas %}
            <p class="mt-lg-5">No Ninjas associated to {{dojo.name}} Dojo.</p>
        {% else %}
            <table class="table table-bordered table-striped text-center mt-lg-5">
                <thead>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Age</th>
                </thead>
                <tbody>
                    {% for ninja in dojo_ninjas %}
                        <tr>
                            <td>{{ninja.first_name}}</td>
                            <td>{{ninja.last_name}}</td>
                            <td>{{ninja.age}}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% endif %}
        <div class="mt-lg-5">
            <a href="{{ url_for('dojo.list_all') }}" class="link-primary">Home</a>
        </div>
    </div>
</div>

{% endblock %}

flask_mysql/crud/Dojos and Ninjas/app/templates/index.html
{% extends "layout.html" %}

{% block title %} Dojos {% endblock title %}

{% block content %}

<div class="row d-flex justify-content-between">
    <div class="col col-md-7">
        <h1>New Dojo</h1>
        <form action="{{ url_for('dojo.create') }}" method="post">
            {{ form.hidden_tag() }}
            {% for field in form %}
                {% if field.name != "csrf_token" and field.type != "SubmitField" %}
                    <div class="row align-items-center">
                        <div class="col-md-2 m-4">
                            {{ field.label(class="form-label") }}:
                        </div>
                        <div class="col-md-5">
                            {{ field(class="form-control") }}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="offset-md-3">
                {{form.submit(class="btn btn-primary")}}
            </div>
        </form>
    </div>
    <div class="col col-md-5">
        <h1>All dojos</h1>
        <div id="dojo_list" class="border border-dark border-2 mt-4">
            {% for dojo in dojos %}
                <div class="m-2">
                    <a href="{{ url_for('dojo.details', id=dojo.id) }}" class="link-primary">{{ dojo.name }}</a>
                </div>
                
            {% endfor %}
        </div>
        <div class="mt-2">
            <a href="{{ url_for('ninja.new_ninja') }}" class="link-primary">Add Ninja</a>
        </div>
    </div>
</div>

{% endblock %}

flask_mysql/crud/Dojos and Ninjas/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Dojos and Ninjas{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='css/style.css')}}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <div class="container m-5">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>